services:
  public-server:
    build: ./public-server
    container_name: public-server
    ports:
      - "8000:8000"
    volumes:
      - ./public-server/files:/app/files
    env_file:
      - ./public-server/.env
    restart: unless-stopped
    networks:
      - private_net

  private-agent:
    build: ./private-agent
    container_name: private-agent
    ports:
      - "8001:8001"
    volumes:
      - ./private-agent/files:/app/files
    env_file:
      - ./private-agent/.env
    restart: unless-stopped
    networks:
      - private_net

# Se definen las redes al final
networks:
  private_net:
    driver: bridge